apply plugin: 'java'
apply plugin: 'application'

repositories {
    mavenCentral()
}

application {
    mainClass = 'com.example.App'

    applicationDefaultJvmArgs = [
        '--add-exports=java.base/sun.security.x509=ALL-UNNAMED'
    ]
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs.add(
        '--add-exports=java.base/sun.security.x509=ALL-UNNAMED'
    )
}
